"""Добавлена колонка доп. информации

Revision ID: 9bedee75b8f5
Revises: ed4848a332a4
Create Date: 2026-01-01 18:32:38.584914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bedee75b8f5'
down_revision = 'ed4848a332a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_information', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('additional_information')

    # ### end Alembic commands ###
