"""Теперь у задач есть свойство is_completed

Revision ID: ab65883a0df6
Revises: e1bd4bc9df60
Create Date: 2026-01-11 23:28:13.702092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab65883a0df6'
down_revision = 'e1bd4bc9df60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('date_of_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
